name: search_github_users
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  #getx state management
  get: ^4.6.1
  #image svg widget
  flutter_svg: ^1.0.3
  #image cache widget
  cached_network_image: ^3.2.0
  #keyboard dismisser
  keyboard_dismisser: ^2.0.1
 #google translation
  translator: ^0.1.7
  number_pagination: ^0.0.3+2

  url_launcher: ^6.0.20

  alice: ^0.2.5

  dio: ^4.0.6
  retrofit: ^3.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: ^2.1.10

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/png/
    - assets/svg/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
